language: python
python:
  - "2.7"
env:
  - DJANGO=1.5.4
install:
  - sudo apt-get install python-dev
  - sudo apt-get install libgeoip-dev
  - sudo pip install geoip
  - pip install -r requirements.txt
before_script:
  - cp mybitbank/settings-template.py mybitbank/settings.py
  - cp mybitbank/libs/connections/walletconfig-template.py mybitbank/libs/connections/walletconfig.py
  - python ./manage.py syncdb --noinput
  - python ./manage.py migrate
script:
  - python ./manage.py test connections
#  - python ./manage.py test login
#  - python ./manage.py test transfer

      
